### ISSUE TITLE
The name of a commentor shows up as the mod creator

### ISSUE THREAD

**Issue by TheGag96** [ModulousSmash/Modulous#1]
Kind of an odd one. [Here](http://modulous.net/mod/232)'s an example. That comment is mine (codeThaumaturge), not Theytah's.

**Comment by EIREXE** [comment]
Thanks for the heads up, i'll get to fix it.

**Comment by EIREXE** [comment]
Fixed in e45595c97085888b532343ceb6e09213d62b862a
