### ISSUE TITLE
It might be time to add a section/tags for Smash 4 mods

### ISSUE THREAD

**Issue by TheGag96** [ModulousSmash/Modulous#3]
We're already able to do moveset edits, music replacements, and texture replacements (possibly models too?). A new section for Sm4sh might be good to help grow a very young community.

**Comment by EIREXE** [comment]
There is catre support, but I must add a distinction for 3ds and wiiu

![2016-02-03_22-12-26](https://cloud.githubusercontent.com/assets/3101690/12797249/48f1839a-cac3-11e5-8d16-c5dddfaf5404.png)

**Comment by EIREXE** [comment]
![sf9qtws 1](https://cloud.githubusercontent.com/assets/3101690/12872952/67fe1000-cdb1-11e5-9c58-3c4b28a55f0a.png)
